apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-push-secret-public-services
  namespace: public-cluster
spec:
  resyncInterval: 1m
  hostAPI: https://infisical.kube.mgmt.nickdann.net/api

  # Optional, defaults to no replacement.
  updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

  # Optional, defaults to no deletion.
  deletionPolicy: Delete # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

  destination:
    projectId: 71c07d53-fd38-4003-ab30-6c1b5c96d41b
    environmentSlug: prod
    secretsPath: /

  push:
    secret:
      secretName: public-services-https-cert
      secretNamespace: public-cluster

  # Only have one authentication method defined or you are likely to run into authentication issues.
  # Remove all except one authentication method.
  authentication:
    kubernetesAuth:
      identityId: 88ff6f63-8b3f-4046-bc22-24833755d5bf
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical