---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter
    namespace: flux-system
  interval: 1h0m0s
  timeout: 20m0s
  valuesFrom:
    - kind: Secret
      name: node-exporter-values
      valuesKey: values.yaml