apiVersion: v1
kind: Secret
metadata:
    name: node-exporter-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: |-
      serviceMonitor:
        enabled: true
        namespace: monitoring
        labels:
          prometheus: main