apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/nginxinc/charts/nginx-ingress
  ref:
    tag: 2.0.0