apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 10m0s
  timeout: 20m0s
  chartRef:
    kind: OCIRepository
    name: nginx-ingress
    namespace: flux-system
  values:
    controller:
      ingressClass:
        name: nginx
      service:
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.100.150
          metallb.universe.tf/allow-shared-ip: "gitea-ssh"