- name: Download FluxCD CLI
  shell: curl -s https://fluxcd.io/install.sh | bash

- name: Install FluxCD components in Kubernetes
  shell: |
    flux install --components-extra=image-reflector-controller,image-automation-controller
  environment:
    KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"

- name: Create FluxCD sops age Secret
  shell: |
    kubectl create secret generic sops-age --namespace flux-system --from-literal=age.agekey={{ age.private }}
  environment:
    KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"
  ignore_errors: true

- name: Create Flux Secret with SSH Key
  shell: |
    flux create secret git flux-system \
      --url=ssh://git@github.com/nxckdx/homelab.git \
      --private-key-file=/home/nick/.ssh/id_ed25519
  environment:
    KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"
  ignore_errors: true

- name: Create FluxCD GitRepository
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      interval: 1m
      url: ssh://git@github.com/nxckdx/homelab.git
      ref:
        branch: main
      secretRef:
        name: flux-system
    EOF
  environment:
    KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"

- name: Create FluxCD Kustomization
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      decryption:
        provider: sops
        secretRef:
          name: sops-age
      interval: 5m
      path: "./flux/clusters/management/apps/flux-system"
      prune: true
      sourceRef:
        kind: GitRepository
        name: flux-system
      validation: client
    EOF
  environment:
    KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"