apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: "2025.2.3"
  interval: 1h0m0s
  timeout: 20m0s
  valuesFrom:
    - kind: Secret
      name: values
      valuesKey: values.yaml