apiVersion: v1
kind: Secret
metadata:
    name: infisical-db-secrets
    namespace: postgres
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: infisical
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Xu2gLK3Nksom,iv:FXABBb2cjNIlo5XcZu/cpxPlmWu8KR9Voe2IljLy//Q=,tag:iy3r2pHFJIr4TF0Dd5V25Q==,type:str]
    password: ENC[AES256_GCM,data:U8LUdBOeBnuhdJEspj9AQu1HwMmJ4VymRFRPxd/v5q4OkJZmXOQXYsTep+pfO6nDeS4Keb2fZcNIZDs=,iv:ruTV20Dzq1tU6KeULPit5CqlMx6iZ1yjxSDhAZDnvjI=,tag:SnHA1A8KhsKfGVBx9kXCPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbi9GYWN2RVhQSXpvcEQr
            andZVXNXRDJpQkgvN3FmSWthNGtwNDhiWEdJCno2d0Noa2cxcXdPanJkS2lwV3FK
            TjRlUlhVTGJhQXZPMWxVeE54VkwvTkkKLS0tIFlia0JZNFVuQ20wb25YN09sVlhW
            MHNmZ2tORzRDdTdFMFU2RUZKM05NNEkK4+BxQifCAE1VnLwX1QBY15HW48DEsPiv
            saqEz2EiCRWjIWJdQ6EetFH/ThSP9HZ56vULulUM3hnBQPR1KTCVsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T17:33:46Z"
    mac: ENC[AES256_GCM,data:Pk4q9FoyIX4bZe+z/mjnl1tGyCLr2s5XhwPZwU50g54D9e5B5dm9+sax91Mm6KBkiSr2lUz+yw9CSW45Us9I9ovTtf7lmvwQJaD9N2gKBLkxFhpybWaW5y6Xd5RDg6MCffdhBJS17pkwKZgnprDib6nBP26BLFdSFKvNDG42Uz0=,iv:lKpuTV9/Ldi8Yx1xdZhkpltjOi23WQeuFqQ5db0sItw=,tag:aDIpdhbfHBpN78CqbWIoIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
