apiVersion: v1
kind: Secret
metadata:
    name: all-secrets
    namespace: infisical
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:9X44HE0nuOlbEWWZPcA=,iv:nNV+UX8DmZTxbO03XprWsQrd7K0AY/ggKP67p1qNlXw=,tag:4pwMJiu1Tyevm/rBeX4RZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7ip3KvoJaeHO6e+GsKex,iv:AnsOEt1NiXksu20suGcauCmK2d03EbJhDybsRY6KIMU=,tag:G8VzZP+Z2yZAGv9lSEwQKQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sLU0gA8dA7Oos9BA,iv:O0iu04IMvO68gom/jsCV00UUbZ1Zp4P6ARLzdP2DrM4=,tag:7U8Gf3qncIMw7cUWyELeAA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:isbk9AbPYUwpUSLS+VbhtGd0cvcb7w+JhjB/AD3QUes=,iv:bYKj044/2gak05b7Tl7vWTtkWR/bE2S2Ba5jTq8Innk=,tag:Lc9OcnFoOOo2cG9GvprThQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:jKlEBMl6cN/IHFqWe22JMa1C9gdWN2MITkZCZLT4GXvE9f02xlM08wVuI0mcYZJ67fyWpYe/flK6ydfSY1yYky02tNspSv4zOCjylg==,iv:Ge+LJoYrrpGmZPmv2LZLfVefPmjzCEno3LIPOeNVpGI=,tag:tpPocqqiEqv4ixaTXujdRg==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:G1mH3o6Yqt1gAL2qaiowfOO3ZgmiRllOHrHNQCNFeCdFxZ/bmW/RxVM6NZ6my2UaweBBlLi0HxAfEr4Q1bb+gnXSC5sAag==,iv:a+xLUSTj4PwOHxvEcfohitts4ns/BLaVEdOPddt589U=,tag:tiAqvjY5E84lxorz3+gNSg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:NPN7kNmzFHkvjPt2H2ypeyTK,iv:LQ8ur2Zk/FOX7oXw6xrhW8QoxOen6r2xQu1Nr+fKM4c=,tag:hCWloQwKXEieOxhG7mRNGw==,type:str]
    SITE_URL: ENC[AES256_GCM,data:ndcFvTlXTEiHNgVd3lvw96fbUsUi2H3FPa2qA/0dHPvZ9kJd43giUQ==,iv:a9lqlJLaeXoial4kN3zXUHtUKmg16/zhyEIwuP+fwMA=,tag:T+sPjpp2dFvoCr5lBPPAmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeFdjNW54ZHBxRXZydk1i
            QTJ5K1BRVitJRDNBcnF4Rkl6emNoWmw5NUhNCkprd2F5YUZsS0RscGxOa3k1dFZo
            WWdxclB2ZUZWeWxhT3c2a3pPT1lzWkkKLS0tIGRyeUY1VWVPQzhJQk9BaFZ2cVR5
            eFd4Zm15QzZ1bkZnNXk1eE5uWDlVSFUK3Iofwst1YxeMC5KAc1w48c7izr9o9x/f
            tv34fcLfy8gcj+jLxSFLg/n4nddhE2wk62gLyEjlmeanAxznLP5s9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T19:09:16Z"
    mac: ENC[AES256_GCM,data:5H0TyRzVTStRs9XxjI4795NdrnEHI567yk5jmInYkeCAzsvGPmQRoUaPltG0XqP6NhXGFaz6HJBnRL5fpbJs5Akvht5dOz61/Ua7+ulkbZV0mmFasLO2qoDUN0mIxmcPwXrjgXUkzqK+EEU+VRMLyRyRDnOROUMyav/0hQCOhMw=,iv:vVK7aqVU1NruR33tgcvOP8eOx9FR3QMpcr4qOnqDIRU=,tag:66gYc/nzB+NVqQ7ce9genQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
