apiVersion: v1
kind: Secret
metadata:
    name: all-secrets
    namespace: infisical
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Yht3DUAKvqmsFM8eGlwX948z701aZ3MVvAvf2t2idY0=,iv:DZbrpP1B2CZc4QYMWxwa+SmXIeY0jn7RNtNRtk2XLCM=,tag:I777RbyNDJ/jOWe0LP0+zQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:DdG7/Tgi6HaOGh0OJaG5Uvcj/tf+I3cja52uR34CN2OrCfVBY1Z1TOcmBxm5IOEP/o03iZxaeOWclSGKfPVO7mtnaIcxdn41cs+KQw==,iv:7JXAvIljkuT4v1EAYrnqECpTuo6Pxm0jp61vjnWddfo=,tag:YWB7HQ/hGaA223xgiWIu7g==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:o6ubChyVF0QequB4ap+B3ZSR4v/D3SrElXZxO8CgRONyXfH4QLHKh4T/WlnS3anXgoR2P3EAGXC4zNRQ7eJp3wEeFxfcsxxbg9eszl4lFcfD/qYHB2uQArRo2wyi1cu9xWVmrO9/PSIgTGtY35XLOQGBUxl2HGcyX6mBZ13sKpOl2z39svae4BAmbvawyk2isY/n,iv:lsgOzJZP6TMEVRU+gA0gnZEGIrJDAEirRHZG22BZNUI=,tag:QA9VPfb+2z64KiciZ5n5Fg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ib999UYvJxVEKWW5W9VgTS1H7pyFPxTlGby7zfHFRmO3HzlKvjIxMACcooA=,iv:3jp63IRqylfCQyRznEJ+pAN+nGBYPKdROR1kIJtAXKo=,tag:7vIX52yTepVtfOFxjJx4mg==,type:str]
    SITE_URL: ENC[AES256_GCM,data:hEUE+fOsZMNOqnDTFSc+IB7PMPmmngdT1LLW06fWeU3WVLqMm0uUrw==,iv:k9aWNHAkGP6OKroADHLhTqIg2MCkLUFQ637L2l+bn94=,tag:l5KhyAIIWgx0a1+TkF7pig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdTRVTFg5UVNBZVpNd0xa
            MHV6TGUyd25yelJkR2dQOTExUlJaeGVSdUNBCmVpMkVaTVgyU3pVQWg4dkFhMG9i
            dXduUU4zZGN3U2RSNDdnMUhQWGUxbGsKLS0tIERIU0Yzd1FicjlQMW05TlY4V2Nv
            MWxaZUlacE9LK0VQZmoxTW5yaFYzN0UKysngIvLG/n0tw2rkpVXZDVsJSDxDXKk8
            aJ4HfnfAmovlokqLpAdgA6pkqPe+ggflMe1KHUShQ7oyvD+d/+zxiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T17:33:39Z"
    mac: ENC[AES256_GCM,data:tdpQmLKhS5w9nLoF11XasHL+1j8YZnoI+xaMoAE1zb7yEjwCSqPiYavH9z2y9evOtfSrn/Fco6d/A3JLcM3aHCUdcCZkR/6Ld0vqjamftEi8Q1Ybsx7cYzAzYs30F+aCwaKEVGJUAiL4AD40k46Drpdd4KlBXN+/x8hf0EADDCQ=,iv:k6fw23T5oiONLm/sdlJ+FXDfFWaTIz9UkPJcnmIsEwY=,tag:E2UMUj36X9lk/e1z+vZTsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
