apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dependencies-crds
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./flux/clusters/management/dependencies/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dependencies-system
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./flux/clusters/management/dependencies/system"
  prune: true
  dependsOn:
  - name: dependencies-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: "./flux/clusters/management/apps"
  prune: true
  dependsOn:
  - name: dependencies-system
  - name: dependencies-crds
  sourceRef:
    kind: GitRepository
    name: flux-system