apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: "./flux/clusters/management/apps/metallb-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: "./flux/clusters/management/apps/nginx-ingress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: "./flux/clusters/management/apps/ceph-csi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: "./flux/clusters/management/apps/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client