apiVersion: v1
kind: Secret
metadata:
    name: grafana-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: |
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: "cloudflare-issuer"
        hosts:
          - grafana.kube.mgmt.nickdann.net
        tls:
          - secretName: grafana-http-tls
            hosts:
              - grafana.kube.mgmt.nickdann.net

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Thanos
              type: prometheus
              access: proxy
              url: http://thanos-query.monitoring.svc.cluster.local:9090
              isDefault: false
              editable: false