apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "8.12.1"
  interval: 1h0m0s
  timeout: 20m0s
  valuesFrom:
    - kind: Secret
      name: grafana-values
      valuesKey: values.yaml