apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cert-manager
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      securityContext:
        seccompProfile:
          type: "RuntimeDefault"
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: favonia/cloudflare-ddns:latest
        name: cloudflare-ddns
        imagePullPolicy: Always
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
        - name: DOMAINS
          value: "jellyfin.nickdann.net"
        - name: PROXIED
          value: "false"
        securityContext:
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false