---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: thanos
    namespace: flux-system
  interval: 1h0m0s
  timeout: 20m0s
  valuesFrom:
    - kind: Secret
      name: thanos-values
      valuesKey: values.yaml