apiVersion: v1
kind: Secret
metadata:
    name: thanos-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: |-
      existingObjstoreSecret: thanos-s3
      
      bucketweb:
        enabled: true
        ingress:
          enabled: true
          hostname: thanos-bucketweb.kube.mgmt.nickdann.net
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: "cloudflare-issuer"
          tls: true
      
      compactor:
        enabled: true
        persistence:
          size: 20Gi

      receive:
        enabled: true
        resources:
          requests:
            cpu: 2
            memory: 512Mi
          limits:
            cpu: 3
            memory: 2048Mi
        persistence:
          size: 20Gi

      storegateway:
        enabled: true