apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gitea
  namespace: gitea
  labels:
    app:  gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gitea
    spec:
      containers:
      - name:  gitea
        image:  docker.gitea.com/gitea:1.23.6
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 800m
            memory: 4Gi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
          - name: GITEA__database__NAME
            value: "gitea-db"
          - name: GITEA__database__USER
            valueFrom:
              secretKeyRef:
                name: gitea-db-secrets
                key: username
          - name: GITEA__database__PASSWD
            valueFrom:
              secretKeyRef:
                name: gitea-db-secrets
                key: password
          - name: GITEA__database__DB_TYPE
            value: "postgres"
          - name: GITEA__database__HOST
            value: "postgres-cluster-rw.postgres.svc.cluster.local"
          
          # Für Cache (wichtig!)
          - name: GITEA__cache__ADAPTER
            value: redis
          - name: GITEA__cache__HOST
            value: redis://redis.redis.svc.cluster.local:6379/10

          # Optional: Für Session-Storage
          - name: GITEA__session__PROVIDER
            value: redis
          - name: GITEA__session__PROVIDER_CONFIG
            value: redis://redis.redis.svc.cluster.local:6379/11

          # Optional: Für Queue (Hintergrund-Jobs)
          - name: GITEA__queue__TYPE
            value: redis
          - name: GITEA__queue__CONN_STR
            value: redis://redis.redis.svc.cluster.local:6379/12
        ports:
        - containerPort:  3000
        - containerPort: 22
          name:  gitea
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
        - name: gitea-data
          mountPath: /data
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
      restartPolicy: Always
