apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      version: "11.0.0"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    service:
      ssh:
        type: LoadBalancer
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
      hosts:
        - host: gitea.kube.mgmt.nickdann.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-http-tls
          hosts:
            - gitea.kube.mgmt.nickdann.net
    persistence:
      storageClass: csi-rbd-sc
      size: 25Gi