apiVersion: v1
kind: ConfigMap
metadata:
    name: ceph-csi-config
    namespace: ceph-csi
data:
    config.json: ENC[AES256_GCM,data:w9rOqykeCsxA1PZ1LBs750CWqYOcfbBgJJYNPumez4T2n61GRU2ga/1VXD3/sOuVaBaVuMazPO4Uud19X4gKsiZqukjApPB5cp6NfV4Mw1mPqO5yHypyhif09GLGjPI3r+28sJMaUgmVhYsP2KKWxNrs1kBm3yb/ng==,iv:8xhQ/uH0eXFup/GAloP+NcgOLhw49WsjcmYnZ89+F2A=,tag:lF6VDUjtMYtQoaq7JFcB6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDZ4UlZnZUlPMERKQlJy
            K0Q4NGFKNnB2Um5MZXFCeWgxb0UwRGtqZWprClRtaitzNjc1bjF1dUM2TlRrNDVM
            ZU16OW0rOEZkUENoNzBLajlvRjJCVlkKLS0tIEV6QlhtK1ZjdFJnZ2sxZmZFUkwv
            SXBUNlJhWER1WUh6MUJYc2cyQjZBbXMKlNgcbU54uNQBFMFuo3Ff7ZRTWlJBZsq5
            Xkxbh1QjPR9Wx8pxUKzLTOMJtVvptPeJ70dX+Gtr2k/yKIP8eydlLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T21:30:13Z"
    mac: ENC[AES256_GCM,data:br+6MJageTUHOa6TFIu2qYpBvyZLuxqABgwvCgYx5w5djr6sgaaRK7BHuO6c2J96qKI01hTvwQJOhzqlumdObhTbeRSZgeh84WfZpoxngIeSAlZVuX0WerjNot35lPWk8m3kPuTA0r5PtGJCOPZNhm+mumemv+4kkPCp7GVi/xc=,iv:RQciTrZMA9bObFP7qmuYHl4kV0cc9k0qGI5ElOIlJw0=,tag:8hO3aFGDryd0bFYzGULWqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ceph-config
    namespace: ceph-csi
data:
    ceph.conf: ENC[AES256_GCM,data:/nET92OwZNOItljJs6zDCg66f3+LjxObWI1j0Vr/pjaPq4sGPRCQm5ZFGf448ztcGFzM7AENEELGe407Ey8WuyvZ2qc+yNpMtJEoM84IfP9i7ITg17tdhlOxhWK3ZeS3AbQ=,iv:RxPdiIfiQBqbYMVLtaxtZ6vQG8XIfhYIeaEJ60kKLM8=,tag:smNXHMyjSV/VHcE0+FI53g==,type:str]
    #ENC[AES256_GCM,data:Jv7idDwODmx0pGoQhrE/nrXVGyaOcwXKYBWY5KsC8OernsMmMSQ4ZJf3YFvT6HudnqM5wU2q2gQ=,iv:tGLtH0HHoRXEpCcit58taWx0KX5HDu86+bM6rG6IRxI=,tag:4i1ogdrSmNRdMqTOVSFPvw==,type:comment]
    keyring: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDZ4UlZnZUlPMERKQlJy
            K0Q4NGFKNnB2Um5MZXFCeWgxb0UwRGtqZWprClRtaitzNjc1bjF1dUM2TlRrNDVM
            ZU16OW0rOEZkUENoNzBLajlvRjJCVlkKLS0tIEV6QlhtK1ZjdFJnZ2sxZmZFUkwv
            SXBUNlJhWER1WUh6MUJYc2cyQjZBbXMKlNgcbU54uNQBFMFuo3Ff7ZRTWlJBZsq5
            Xkxbh1QjPR9Wx8pxUKzLTOMJtVvptPeJ70dX+Gtr2k/yKIP8eydlLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T21:30:13Z"
    mac: ENC[AES256_GCM,data:br+6MJageTUHOa6TFIu2qYpBvyZLuxqABgwvCgYx5w5djr6sgaaRK7BHuO6c2J96qKI01hTvwQJOhzqlumdObhTbeRSZgeh84WfZpoxngIeSAlZVuX0WerjNot35lPWk8m3kPuTA0r5PtGJCOPZNhm+mumemv+4kkPCp7GVi/xc=,iv:RQciTrZMA9bObFP7qmuYHl4kV0cc9k0qGI5ElOIlJw0=,tag:8hO3aFGDryd0bFYzGULWqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
