apiVersion: v1
kind: ConfigMap
metadata:
    name: ceph-csi-config
    namespace: ceph-csi
data:
    config.json: ENC[AES256_GCM,data:8zpxsbAgMk5DgdqcdOmrGMszGfnodwzXdL6boEJJIjeJNAfFV6RBnDzd551LqJlFXA2IHPg86Ifma9KDPeXS2c1HCfwpdqdpTUPV722w+CSaWqx9KC8Q3qtROrtqBHwij+4esnNJJ8H92867Kd6VVMRYXLXz2/A2Gg==,iv:1oUlRuFAFMkMir3Gp+BYiaFAPS89uuDBnQcKuEfAbTA=,tag:Yvxo8Q3IOwUXMEaFfMCtNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3ZpYkllSzdDaW1TL2J2
            TlV4b3d4MW9VdS9kbWgrLzErRzlTS0JOVnhJCnZoM0RleWlCMlVzM1N6RDBMK0Jw
            OURJTmNwb0VmZ0ZTbHpidnpVVk41TDAKLS0tIEc2WXVmQThvQnppSmwrb1BLZEM3
            dFJMT3dYcEtkMFVPL2hzR2daSUpqT1UKmhC0zoVxYbXeeQINkCh81IsFASP2/RNv
            7fZjUIKfcuqmU90GjMYsTQCpt4zvy5dkq82BJQeRPFtTxgw2Wli24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T21:35:34Z"
    mac: ENC[AES256_GCM,data:ICnTFoNDrSszA33FfO/SauxJ0OxRjaG7k/sM++r70rc3C0AwAyTLGZN4HX1qK0jWnHhQ1UsVt4IRlNZeEV1G91HrpIYdWJCCJURoejM8UCozsdmKbKA5UWGSwqDOoYo37WMf4UJ7LMUH54p1RVnO3KiusHf+9rtzrLHDy9ONogs=,iv:CXSxelQaNuaxJieDSAGxUEAuwgl7HZWYYZJ7yeOeAIc=,tag:sHCGJxh4ubg2nzG3p3pGFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ceph-config
    namespace: ceph-csi
data:
    ceph.conf: ENC[AES256_GCM,data:yKfOr+JrKy4YyKTYHR/dq5++eH2YZXvEpHoTC/6dJiRLxjhuFVgvKiDIBNUXtoPxRnl0FJ6+spX/RBCP/HrFYkmAkO09lgMu+tGwbB/W4/SU6MEIJqieABfWUbs33LbuiGM=,iv:lDtKfsMVRe/yZM+xvAZUrBfA8GQzfesMwmyxJTpoE9A=,tag:euA1iXWvfTMsCSoT3q/4tQ==,type:str]
    #ENC[AES256_GCM,data:Yjw85wFoFvlVUIbxDYMVpo1YzoeZdJeWB0nFMkbre3gb1NStx/MtyZ5dkCjSIPc9QqKFzfrWnj8=,iv:MIaNRlJOGfgLewTSu6gMgk6aJCNA+XoktMI+xLx4Pv0=,tag:vh73zIzitKe2bihpuQH+7A==,type:comment]
    keyring: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3ZpYkllSzdDaW1TL2J2
            TlV4b3d4MW9VdS9kbWgrLzErRzlTS0JOVnhJCnZoM0RleWlCMlVzM1N6RDBMK0Jw
            OURJTmNwb0VmZ0ZTbHpidnpVVk41TDAKLS0tIEc2WXVmQThvQnppSmwrb1BLZEM3
            dFJMT3dYcEtkMFVPL2hzR2daSUpqT1UKmhC0zoVxYbXeeQINkCh81IsFASP2/RNv
            7fZjUIKfcuqmU90GjMYsTQCpt4zvy5dkq82BJQeRPFtTxgw2Wli24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T21:35:34Z"
    mac: ENC[AES256_GCM,data:ICnTFoNDrSszA33FfO/SauxJ0OxRjaG7k/sM++r70rc3C0AwAyTLGZN4HX1qK0jWnHhQ1UsVt4IRlNZeEV1G91HrpIYdWJCCJURoejM8UCozsdmKbKA5UWGSwqDOoYo37WMf4UJ7LMUH54p1RVnO3KiusHf+9rtzrLHDy9ONogs=,iv:CXSxelQaNuaxJieDSAGxUEAuwgl7HZWYYZJ7yeOeAIc=,tag:sHCGJxh4ubg2nzG3p3pGFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ceph-csi-encryption-kms-config
    namespace: ceph-csi
data:
    config.json: ENC[AES256_GCM,data:qJQ=,iv:1fbPc9jPY2ykJ+Qk8W8m8tpj9NXd9zOJ+TamxGc8fsw=,tag:JmZCS+wOtPOiIIK40J/SWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3ZpYkllSzdDaW1TL2J2
            TlV4b3d4MW9VdS9kbWgrLzErRzlTS0JOVnhJCnZoM0RleWlCMlVzM1N6RDBMK0Jw
            OURJTmNwb0VmZ0ZTbHpidnpVVk41TDAKLS0tIEc2WXVmQThvQnppSmwrb1BLZEM3
            dFJMT3dYcEtkMFVPL2hzR2daSUpqT1UKmhC0zoVxYbXeeQINkCh81IsFASP2/RNv
            7fZjUIKfcuqmU90GjMYsTQCpt4zvy5dkq82BJQeRPFtTxgw2Wli24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T21:35:34Z"
    mac: ENC[AES256_GCM,data:ICnTFoNDrSszA33FfO/SauxJ0OxRjaG7k/sM++r70rc3C0AwAyTLGZN4HX1qK0jWnHhQ1UsVt4IRlNZeEV1G91HrpIYdWJCCJURoejM8UCozsdmKbKA5UWGSwqDOoYo37WMf4UJ7LMUH54p1RVnO3KiusHf+9rtzrLHDy9ONogs=,iv:CXSxelQaNuaxJieDSAGxUEAuwgl7HZWYYZJ7yeOeAIc=,tag:sHCGJxh4ubg2nzG3p3pGFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
