apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "34.5.0"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    ingressClass:
      name: traefik
    deployment:
      kind: DaemonSet
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    additionalArguments:
      - "--api.insecure=true"
    extraObjects:
      - apiVersion: v1
        kind: Service
        metadata:
          name: traefik-api
          namespace: traefik
        spec:
          type: ClusterIP
          selector:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-default
          ports:
            - port: 8080
              name: traefik
              targetPort: 8080
              protocol: TCP

      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: traefik-dashboard
          namespace: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: "cloudflare-issuer"
        spec:
          rules:
            - host: traefik.kube.mgmt.nickdann.net
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: traefik-api
                        port:
                          name: traefik
          tls:
            - secretName: traefik-dashboard-tls
              hosts:
                - traefik.kube.mgmt.nickdann.net