apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "34.5.0"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    deployment:
      enabled: true
      kind: DaemonSet
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/sharing-key: homelab
        lbipam.cilium.io/sharing-cross-namespace: "*"
      spec:
        loadBalancerIP: "192.168.100.150"
        externalTrafficPolicy: "Cluster"
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["traefik", "web", "websecure"]
        matchRule: Host(`traefik.kube.mgmt.nickdann.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
        annotations:
          cert-manager.io/cluster-issuer: "cloudflare-issuer"
        tls:
          secretName: traefik-dashboard-tls
          domains:
            - main: traefik.kube.mgmt.nickdann.net
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    additionalArguments:
      - "--api.insecure=true"
    extraObjects:
      - apiVersion: v1
        kind: Service
        metadata:
          name: traefik-api
          namespace: traefik
        spec:
          type: ClusterIP
          selector:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-default
          ports:
            - port: 8080
              name: traefik
              targetPort: 8080
              protocol: TCP