apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-secrets
    namespace: postgres
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: harbor
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pov4ySdk,iv:4P+M6RntHPOoLm9QbgITKVXe8bUvJlfJ4tArT8gytjw=,tag:dvdcnpj/qhatNTPQZcB8pg==,type:str]
    password: ENC[AES256_GCM,data:moUixJ8tw05TLmiiMeECtITzoalebMwRxXVV6nPAqdNO/h7SG6M1Emv2DFbba102Z226KDE=,iv:PU6VU3Gxjkk38llFPULCT6In5FKGuFRDJBrjQpAYB88=,tag:2ax6yI+MyXGkymlx7A5UTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10d9p4k0wlwwznf4dprjnjf702p59yr76etfd0dgzlajezpmzu9gq6qhhus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRUpidGwzWEtBanhRcktx
            MGQ0NC9XeCtqcVVId0Vwc1JEVlcycGdHczAwCmZ6Y2RWTHEvZVJjLzRiN2FkUmJV
            Qkl1SlNZN09JaVpOUFFmSHJ5U0JhVzQKLS0tIHAxenlWR0Zvemp5MU9aN1VXNGps
            Tjc0eFVwb3RHQ04vMm9jdTNOOVVjNzAKSz2sIeM4+f2D/bYX5fy8/7jCHZBemqzO
            HaMPRs0+elQaNfMYFhulsg8uj8Jh91HbBA5j3k+xndoMKhtM/4e+GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T17:12:11Z"
    mac: ENC[AES256_GCM,data:5x0yXmJzgeltmn/0sXUk6Krfs04/BHfxu1n18HxzacXun+GYWRSM2I/ATPLoOBxvgAJLjadGZhUzcKNokp4QcRsFuR8POUdMVA3kMEvvr31F+VRwM28mh0lE1ufiHL7FG1msQSVWRZyidwIDDyqquzAg4IgW2wA15a0JfPVz+bQ=,iv:eC45me7xNxgqYOdAL3OGTslSg5JC+8jVDRjAFQ6D9OM=,tag:+jFQ7LyrdOmdvC0/MM87MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
