apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: "1.16.2"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    expose:
      type: ingress
      tls:
        certSource: secret
        secret:
          secretName: harbor-tls-ssl
      ingress:
        hosts:
          core: harbor.kube.mgmt.nickdann.net
        className: traefik
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: "cloudflare-issuer"
    externalURL: https://harbor.kube.mgmt.nickdann.net
    database:
      type: external
      external:
        host: "postgres-cluster-rw.postgres.svc.cluster.local"
        port: "5432"
        username: harbor
        existingSecret: harbor-db-secrets # The Password
        coreDatabase: "harbor-db"
    redis:
      type: external
      external:
        addr: "redis.redis.svc.cluster.local:6379"
    persistence:
      imageChartStorage:
        # must be set true, because of MinIO
        disableredirect: true
        type: s3
        s3:
          existingSecret: "minio-secret"
          bucket: harbor
          regionendpoint: https://minio.local.nickdann.net
          secure: false
          v4auth: true
          rootdirectory: /
          encrypt: false
      persistentVolumeClaim:
        jobservice:
          jobLog:
            storageClass: csi-rbd-sc
            size: 5Gi
        trivy:
          storageClass: csi-rbd-sc
          size: 10Gi