apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 10m0s
  chartRef:
    kind: OCIRepository
    name: nginx-ingress
    namespace: flux-system
  values:
    controller:
      ingressClass:
        name: nginx