apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-latest
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
      version: "2.10.3"
  interval: 1h0m0s
  values:
    agentTLSMode: system-store
    ingress:
      enabled: true
      ingressClassName: nginx
      extraAnnotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
      tls:
        source: secret
    replicas: 2
    hostname: rancher.kube.mgmt.nickdann.net