apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-snmp-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "9.2.1"
  interval: 1h0m0s
  timeout: 3m0s
  valuesFrom:
    - kind: Secret
      name: snmp-exporter-values
      valuesKey: values.yaml