apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-snmp-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "9.1.0"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
      hosts:
        - "snmp-exporter.kube.mgmt.nickdann.net"
      tls:
        - secretName: snmp-exporter-ssl-tls
          hosts:
            - "snmp-exporter.kube.mgmt.nickdann.net"