apiVersion: v1
kind: Secret
metadata:
    name: snmp-exporter-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: |-
      extraArgs:
        - "--config.file=/etc/snmp_exporter/snmp.yml"
      config: |-
        auths:
          custom_community:
            community: asdfasdf
        modules:
          if_mib_custom:
            auth: custom_community
            walk:
              - 1.3.6.1.2.1.1
              - 1.3.6.1.2.1.2
      serviceMonitor:
        enabled: true
        relabelings:
          - sourceLabels: [__param_target]
            targetLabel: instance
        params:
          - module:
              - if_mib_custom
            name: netgear-switch
            target: 192.168.178.200
        selector:
          prometheus: main
        selfMonitor:
          enabled: true
          additionalMetricsRelabels: {}
          additionalRelabeling: []
          labels:
            prometheus: main
          path: /metrics
          scheme: http
          tlsConfig: {}
          interval: 30s
          scrapeTimeout: 30s