apiVersion: v1
kind: Secret
metadata:
    name: snmp-exporter-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: |-
      extraArgs:
        - "--config.file=/etc/snmp_exporter/snmp.yml"
      config: |-
        auths:
          custom_v2:
            community: asdfasdf
            security_level: noAuthNoPriv
            auth_protocol: MD5
            priv_protocol: DES
            version: 2
      serviceMonitor:
        enabled: true
        relabelings:
          - sourceLabels: [__param_target]
            targetLabel: instance
        params:
          - module:
              - if_mib
            name: wlan-ap
            target: 192.168.178.61
          - module:
              - if_mib
            name: netgear-switch
            target: 192.168.178.200
        selector:
          prometheus: main
        selfMonitor:
          enabled: true
          additionalMetricsRelabels: {}
          additionalRelabeling: []
          labels:
            prometheus: main
          path: /metrics
          scheme: http
          tlsConfig: {}
          interval: 30s
          scrapeTimeout: 30s