- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_check

- name: Initialize Kubernetes master node
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not kubeadm_init_check.stat.exists
  register: kubeadm_init

- name: Copy admin.conf to Ansible Control Node
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ playbook_dir }}/../kubeconfig"
    flat: yes

- name: Install Kubernetes network plugin (Flannel)
  shell: |
    kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml --kubeconfig /etc/kubernetes/admin.conf
    