apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 30s
      path: /snmp
      params:
        module: [if_mib]
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: prometheus-snmp-exporter.monitoring.svc:9116
