apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: homer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc