apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "70.3.0"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: csi-rbd-sc
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    thanosRuler:
      thanosRulerSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-rbd-sc
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: csi-rbd-sc
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 35Gi
        additionalScrapeConfigs:
          - job_name: 'snmp'
            metrics_path: /snmp
            params:
              module: [if_mib]
            static_configs:
              - targets:
                - 192.168.178.61
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: prometheus-snmp-exporter.monitoring.svc:9116
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "cloudflare-issuer"
        hosts:
          - "grafana.kube.mgmt.nickdann.net"
        path: /
        tls:
          - secretName: grafana-ssl-tls
            hosts:
              - "grafana.kube.mgmt.nickdann.net"