- name: Wait for SSH to be available on all nodes
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait 300 seconds for connection
      ansible.builtin.wait_for_connection:
        delay: 0
        timeout: 300

- name: Copy kubeconfig to localhost
  hosts: kube_control_plane
  gather_facts: false
  become: true
  tasks:
    - name: Copy admin.conf to Ansible Control Node
      fetch:
        src: /etc/kubernetes/super-admin.conf
        dest: "{{ playbook_dir }}/../kubeconfig"
        flat: yes
      run_once: true

- hosts: localhost
  become: true
  roles:
    - cilium
  vars_files:
    - ../secret.yaml


- hosts: localhost
  become: true
  roles:
    - flux
  vars_files:
    - ../secret.yaml
