apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
  namespace: gitlab
spec:
  secretName: gitlab-tls
  dnsNames:
  - kas.kube.mgmt.nickdann.net
  - minio.kube.mgmt.nickdann.net
  - registry.kube.mgmt.nickdann.net
  - gitlab.kube.mgmt.nickdann.net
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io