apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.100.150"
      stop: "192.168.100.200"

  serviceSelector:
    matchLabels:
      cilium-lb-pool: ip-pool