apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
spec:
  # serviceSelector:
  #   matchLabels:
  #     cilium-lb-pool: ip-pool
  loadBalancerIPs: true