apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "1.17.1"
  interval: 1h0m0s
  timeout: 20m0s
  values:
    startupapicheck:
      enabled: false
    crds:
      enabled: false
    extraArgs:
    - "--dns01-recursive-nameservers-only"
    - "--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53"
    # prometheus:
    #   enabled: true
    #   servicemonitor:
    #     enabled: true
    #     namespace: monitoring